name: chat_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  rxdart: ^0.28.0
  bloc: ^8.1.4
  get_it: ^7.7.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  firebase_auth: ^5.1.1
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/localization/l10n
  preferred-supported-locales:
    - ru
  use-deferred-loading: true